In [1]:
import sqlite3, pandas as pd

In [2]:
con = sqlite3.connect("domain_tagger.db")

In [3]:
# See all runs
pd.read_sql("SELECT * FROM runs", con)

,run_id,run_name,source,domain_labels,threshold,created_at
0,68658ac3,Run — 28 Mar 18:17,"{""source"": ""file_upload""}","[""Accounts"", ""Customer"", ""Email"", ""Employee"", ...",0.25,2026-03-28 18:17

In [5]:
# Full results for a specific run
pd.read_sql("SELECT * FROM tagging_results WHERE run_id = '68658ac3'", con)

,id,run_id,table_name,domain,auto_domain,score,columns,text_used
0,1,68658ac3,sales_orders,Sales,Sales,0.900,"[""probability"", ""order_date"", ""lead_source"", ""...",sales_orders probability order_date lead_sourc...
1,2,68658ac3,order_line_items,Sales,Sales,0.718,"[""discount_pct"", ""close_date"", ""opportunity_id...",order_line_items discount_pct close_date oppor...
2,3,68658ac3,order_header,Sales,Sales,0.864,"[""stage"", ""channel"", ""sales_rep_id"", ""lead_sou...",order_header stage channel sales_rep_id lead_s...
3,4,68658ac3,order_details,Sales,Sales,0.897,"[""unit_price"", ""probability"", ""attainment_pct""...",order_details unit_price probability attainmen...
4,5,68658ac3,sales_transactions,Sales,Sales,0.686,"[""probability"", ""campaign_id"", ""opportunity_id...",sales_transactions probability campaign_id opp...
...,...,...,...,...,...,...,...,...
495,496,68658ac3,research_grants,Student,Student,0.854,"[""graduation_date"", ""attendance_pct"", ""departm...",research_grants graduation_date attendance_pct...
496,497,68658ac3,student_housing,Student,Student,0.894,"[""gpa"", ""section"", ""major"", ""credits"", ""room_n...",student_housing gpa section major credits room...
497,498,68658ac3,extracurricular_activities,Student,Student,0.888,"[""tuition_amount"", ""gpa"", ""attendance_pct"", ""d...",extracurricular_activities tuition_amount gpa ...
498,499,68658ac3,alumni_records,Student,Student,0.889,"[""aid_amount"", ""scholarship_name"", ""exam_score...",alumni_records aid_amount scholarship_name exa...
499,500,68658ac3,admissions_applications,Student,Student,0.857,"[""student_id"", ""aid_amount"", ""department"", ""ma...",admissions_applications student_id aid_amount ...

In [6]:
# All overrides
pd.read_sql("SELECT * FROM user_overrides", con)

Empty DataFrame
Columns: [id, run_id, table_name, new_domain, overridden_at]
Index: []

In [1]:
# Trino check
from trino.dbapi import connect
from trino.auth import BasicAuthentication
import pandas as pd
import numpy as np
from datetime import datetime
 
# Connect to Trino
conn = connect(
    host="tcp.known-racer.mydataos.com",
    port=7432,
    auth=BasicAuthentication("gunasekaranraja", "ZGF0YV9tb2RlbGVyLmM0MTQ0MzU0LWNhYmYtNDM0Zi1iYzFhLTI1OWFjYTFlMTYxMA=="),
    http_scheme="https",
    http_headers={"cluster-name": "minervac"}
)
 
# Query devices
query = """ 
SELECT
    d_id as device_id
FROM
    "icebase"."customer_360".customer
"""
device_df = pd.read_sql(query, conn)
 
 
print(device_df.head(20))
print(device_df.columns)
# device_df.to_csv("disk_failure_prediction.csv",index=False)

C:\Users\Nivedhaa\AppData\Local\Temp\ipykernel_8944\4255080856.py:24: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  device_df = pd.read_sql(query, conn)

DatabaseError: Execution failed on sql:
SELECT
    d_id as device_id
FROM
    "icebase"."customer_360".customer

TrinoUserError(type=USER_ERROR, name=COLUMN_NOT_FOUND, message="line 3:5: Column 'd_id' cannot be resolved", query_id=20260330_111600_01486_q8p5j)
unable to rollback

In [3]:
from trino.dbapi import connect
from trino.auth import BasicAuthentication
import pandas as pd

# Connect to Trino
conn = connect(
    host="tcp.known-racer.mydataos.com",
    port=7432,
    auth=BasicAuthentication(
        "gunasekaranraja",
        "ZGF0YV9tb2RlbGVyLmM0MTQ0MzU0LWNhYmYtNDM0Zi1iYzFhLTI1OWFjYTFlMTYxMA=="
    ),
    http_scheme="https",
    http_headers={"cluster-name": "minervac"}
)

# Execute query
cur = conn.cursor()
cur.execute("""
                SELECT * FROM "icebase"."customer_360".customer LIMIT 10
            """)

# Get column names from cursor description
column_names = [desc[0] for desc in cur.description]

# Fetch rows and convert to DataFrame
rows = cur.fetchall()
df = pd.DataFrame(rows, columns=column_names)

# df
# Save to CSV
# df.to_csv("manage_upload.csv", index=False)

# Print the DataFrame
# print(df)
df

,customer_id,external_customer_ref,first_name,last_name,email,phone_e164,birth_date,gender,country_code,signup_channel,signup_at,is_active,created_at,updated_at
0,1,CUST-00000001,Daniel,Hill,daniel.hill.227@doyle.net,001-260-501-3389,1985-08-10,female,GB,web,2024-03-09 22:32:44.879081,False,2024-03-09 22:32:44.879081,2024-03-09 22:32:44.879081
1,2,CUST-00000002,Robert,Wright,robert.wright.282@wolfe.com,651.216.1559,1973-08-11,female,GB,store,2025-08-22 22:32:44.879081,True,2025-08-22 22:32:44.879081,2025-08-22 22:32:44.879081
2,3,CUST-00000003,Teresa,Ferguson,teresa.ferguson.972@hurst.com,+1-634-313-1647x52553,1984-09-01,female,US,web,2023-12-11 22:32:44.879081,True,2023-12-11 22:32:44.879081,2023-12-11 22:32:44.879081
3,4,CUST-00000004,Jessica,Ford,jessica.ford.753@holmes.com,9568413953,1973-07-29,female,CA,web,2025-06-28 22:32:44.879081,True,2025-06-28 22:32:44.879081,2025-06-28 22:32:44.879081
4,5,CUST-00000005,Bradley,Mcgee,bradley.mcgee.642@burgess-patterson.org,+441314960328,1950-05-24,male,US,app,2025-08-05 22:32:44.879081,True,2025-08-05 22:32:44.879081,2025-08-05 22:32:44.879081
5,6,CUST-00000006,Michelle,Burton,michelle.burton.570@carlson-cruz.org,(0191) 496 0480,1990-01-26,female,GB,web,2025-07-23 22:32:44.879081,True,2025-07-23 22:32:44.879081,2025-07-23 22:32:44.879081
6,7,CUST-00000007,Nicole,Read,nicole.read.996@harris.info,001-248-728-1489x3252,1945-11-23,male,IT,marketing,2025-07-30 22:32:44.879081,True,2025-07-30 22:32:44.879081,2025-07-30 22:32:44.879081
7,8,CUST-00000008,Mohammad,Brown,mohammad.brown.805@miller.com,927 824 8963,1988-02-16,male,GB,app,2025-06-28 22:32:44.879081,False,2025-06-28 22:32:44.879081,2025-06-28 22:32:44.879081
8,9,CUST-00000009,Larry,Santos,larry.santos.714@price.com,(439) 301-0310 x518,1986-10-24,male,IT,web,2025-05-01 22:32:44.879081,True,2025-05-01 22:32:44.879081,2025-05-01 22:32:44.879081
9,10,CUST-00000010,Amber,Walls,amber.walls.153@kennedy.com,865-766-7010,1960-05-01,female,CA,web,2025-06-26 22:32:44.879081,True,2025-06-26 22:32:44.879081,2025-06-26 22:32:44.879081