In [1]:
import sqlite3, pandas as pd

In [2]:
con = sqlite3.connect("domain_tagger.db")

In [3]:
# See all runs
pd.read_sql("SELECT * FROM runs", con)

,run_id,run_name,source,domain_labels,threshold,created_at
0,68658ac3,Run — 28 Mar 18:17,"{""source"": ""file_upload""}","[""Accounts"", ""Customer"", ""Email"", ""Employee"", ...",0.25,2026-03-28 18:17

In [5]:
# Full results for a specific run
pd.read_sql("SELECT * FROM tagging_results WHERE run_id = '68658ac3'", con)

,id,run_id,table_name,domain,auto_domain,score,columns,text_used
0,1,68658ac3,sales_orders,Sales,Sales,0.900,"[""probability"", ""order_date"", ""lead_source"", ""...",sales_orders probability order_date lead_sourc...
1,2,68658ac3,order_line_items,Sales,Sales,0.718,"[""discount_pct"", ""close_date"", ""opportunity_id...",order_line_items discount_pct close_date oppor...
2,3,68658ac3,order_header,Sales,Sales,0.864,"[""stage"", ""channel"", ""sales_rep_id"", ""lead_sou...",order_header stage channel sales_rep_id lead_s...
3,4,68658ac3,order_details,Sales,Sales,0.897,"[""unit_price"", ""probability"", ""attainment_pct""...",order_details unit_price probability attainmen...
4,5,68658ac3,sales_transactions,Sales,Sales,0.686,"[""probability"", ""campaign_id"", ""opportunity_id...",sales_transactions probability campaign_id opp...
...,...,...,...,...,...,...,...,...
495,496,68658ac3,research_grants,Student,Student,0.854,"[""graduation_date"", ""attendance_pct"", ""departm...",research_grants graduation_date attendance_pct...
496,497,68658ac3,student_housing,Student,Student,0.894,"[""gpa"", ""section"", ""major"", ""credits"", ""room_n...",student_housing gpa section major credits room...
497,498,68658ac3,extracurricular_activities,Student,Student,0.888,"[""tuition_amount"", ""gpa"", ""attendance_pct"", ""d...",extracurricular_activities tuition_amount gpa ...
498,499,68658ac3,alumni_records,Student,Student,0.889,"[""aid_amount"", ""scholarship_name"", ""exam_score...",alumni_records aid_amount scholarship_name exa...
499,500,68658ac3,admissions_applications,Student,Student,0.857,"[""student_id"", ""aid_amount"", ""department"", ""ma...",admissions_applications student_id aid_amount ...

In [6]:
# All overrides
pd.read_sql("SELECT * FROM user_overrides", con)

Empty DataFrame
Columns: [id, run_id, table_name, new_domain, overridden_at]
Index: []

In [1]:
# Trino check
from trino.dbapi import connect
from trino.auth import BasicAuthentication
import pandas as pd
import numpy as np
from datetime import datetime
 
# Connect to Trino
conn = connect(
    host="tcp.known-racer.mydataos.com",
    port=7432,
    auth=BasicAuthentication("gunasekaranraja", "ZGF0YV9tb2RlbGVyLmM0MTQ0MzU0LWNhYmYtNDM0Zi1iYzFhLTI1OWFjYTFlMTYxMA=="),
    http_scheme="https",
    http_headers={"cluster-name": "minervac"}
)
 
# Query devices
query = """ 
SELECT
    d_id as device_id
FROM
    "icebase"."customer_360".customer
"""
device_df = pd.read_sql(query, conn)
 
 
print(device_df.head(20))
print(device_df.columns)
# device_df.to_csv("disk_failure_prediction.csv",index=False)

C:\Users\Nivedhaa\AppData\Local\Temp\ipykernel_8944\4255080856.py:24: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  device_df = pd.read_sql(query, conn)

DatabaseError: Execution failed on sql:
SELECT
    d_id as device_id
FROM
    "icebase"."customer_360".customer

TrinoUserError(type=USER_ERROR, name=COLUMN_NOT_FOUND, message="line 3:5: Column 'd_id' cannot be resolved", query_id=20260330_111600_01486_q8p5j)
unable to rollback

### salesforce_projects_resource

In [5]:
from trino.dbapi import connect
from trino.auth import BasicAuthentication
import pandas as pd

# Connect to Trino
conn = connect(
    host="tcp.known-racer.mydataos.com",
    port=7432,
    auth=BasicAuthentication(
        "gunasekaranraja",
        "ZGF0YV9tb2RlbGVyLmM0MTQ0MzU0LWNhYmYtNDM0Zi1iYzFhLTI1OWFjYTFlMTYxMA=="
    ),
    http_scheme="https",
    http_headers={"cluster-name": "minervac"}
)

# Execute query
cur = conn.cursor()
cur.execute("""
                SELECT * FROM "icebase"."portfolio_intel".salesforce_projects_resource LIMIT 10
            """)

# Get column names from cursor description
column_names = [desc[0] for desc in cur.description]

# Fetch rows and convert to DataFrame
rows = cur.fetchall()
df = pd.DataFrame(rows, columns=column_names)
pd.set_option('display.max_columns', None)

# df
# Save to CSV
# df.to_csv("manage_upload.csv", index=False)

# Print the DataFrame
# print(df)
df

,pk,salesforce_id,name,stage_name,close_date,description,created_date,last_modified_date,is_closed,is_won,is_deleted,is_private,probability,forecast_category,forecast_category_name,has_opportunity_line_item,owner_id,created_by_id,last_modified_by_id,system_modstamp,push_count,fiscal_quarter,fiscal_year,fiscal,last_viewed_date,last_referenced_date,has_open_activity,has_overdue_task,_object,_nilus_load_id,_nilus_id,project_id,portfolio_id,program_id,project_code,project_name,project_type,lifecycle_state,stage,start_date,end_date,strategic_alignment_flag,business_value_validated_flag,sponsor_person_id,owning_org,created_at,updated_at
0,006T100000Q79kSIAR,006T100000Q79kSIAR,Clinical Modernization Initiative 1,Prospecting,2026-12-31,modernization initiative for Clinical Moderniz...,2026-03-05 11:03:47+00:00,2026-03-05 11:03:47+00:00,False,False,False,False,0.0,Closed,Closed,False,005f60000029rvfAAA,005f60000029rvfAAA,005f60000029rvfAAA,2026-03-05 11:03:47+00:00,0,4,2026,2026 4,2026-03-05 11:03:47+00:00,2026-03-05 11:03:47+00:00,False,False,Opportunity,1772717581.9591372,yqaV4wH3rN4KcA,3a7051f4-6b57-46c0-b378-d9f316dcf5bc,424b1fee-9709-4315-85d9-5954058b4714,5f5ff932-5cd7-44de-b84f-1b0e758075ba,KP-50031-1,,,approved,,,,,,,Clinical IT,2026-03-05 11:03:47+00:00,2026-03-05 11:03:47+00:00
1,006T100000Q79kTIAR,006T100000Q79kTIAR,Clinical Modernization Initiative 2,Negotiation/Review,2026-01-09,modernization initiative for Clinical Moderniz...,2026-03-05 11:03:48+00:00,2026-03-05 11:03:48+00:00,False,False,False,False,0.0,Closed,Closed,False,005f60000029rvfAAA,005f60000029rvfAAA,005f60000029rvfAAA,2026-03-05 11:03:48+00:00,0,1,2026,2026 1,2026-03-05 11:03:48+00:00,2026-03-05 11:03:48+00:00,False,False,Opportunity,1772717581.9591372,ioocugLBRB/vzg,daae9339-27d9-42fa-863f-cb7b350b801b,424b1fee-9709-4315-85d9-5954058b4714,5f5ff932-5cd7-44de-b84f-1b0e758075ba,KP-16788-2,,,closed,,,,,,,Digital Health,2026-03-05 11:03:48+00:00,2026-03-05 11:03:48+00:00
2,006T100000Q7G2nIAF,006T100000Q7G2nIAF,Clinical Modernization Initiative 3,Proposal/Price Quote,2026-12-31,modernization initiative for Clinical Moderniz...,2026-03-05 11:03:48+00:00,2026-03-05 11:03:48+00:00,False,False,False,False,0.0,Closed,Closed,False,005f60000029rvfAAA,005f60000029rvfAAA,005f60000029rvfAAA,2026-03-05 11:03:48+00:00,0,4,2026,2026 4,2026-03-05 11:03:48+00:00,2026-03-05 11:03:48+00:00,False,False,Opportunity,1772717581.9591372,ykIX1jo8Z50O7g,6fb1cdae-5c97-45a2-b590-15ed96a3499d,424b1fee-9709-4315-85d9-5954058b4714,5f5ff932-5cd7-44de-b84f-1b0e758075ba,KP-58172-3,,,in_flight,,,,,,,Platform Eng,2026-03-05 11:03:48+00:00,2026-03-05 11:03:48+00:00
3,006T100000Q7EiVIAV,006T100000Q7EiVIAV,Clinical Regulatory Initiative 4,Qualification,2026-12-31,regulatory initiative for Clinical Modernizati...,2026-03-05 11:03:49+00:00,2026-03-05 11:03:49+00:00,False,False,False,False,0.0,Closed,Closed,False,005f60000029rvfAAA,005f60000029rvfAAA,005f60000029rvfAAA,2026-03-05 11:03:49+00:00,0,4,2026,2026 4,2026-03-05 11:03:49+00:00,2026-03-05 11:03:49+00:00,False,False,Opportunity,1772717581.9591372,eCMbH1iROkL54w,1eb9b351-a0c5-4f99-9b45-1cd444e301c5,424b1fee-9709-4315-85d9-5954058b4714,5f5ff932-5cd7-44de-b84f-1b0e758075ba,KP-43196-4,,,intake,,,,,,,Platform Eng,2026-03-05 11:03:49+00:00,2026-03-05 11:03:49+00:00
4,006T100000Q7NIkIAN,006T100000Q7NIkIAN,Clinical Regulatory Initiative 5,Negotiation/Review,2025-06-14,regulatory initiative for Clinical Modernizati...,2026-03-05 11:03:50+00:00,2026-03-05 11:03:50+00:00,False,False,False,False,0.0,Closed,Closed,False,005f60000029rvfAAA,005f60000029rvfAAA,005f60000029rvfAAA,2026-03-05 11:03:50+00:00,0,2,2025,2025 2,2026-03-05 11:03:50+00:00,2026-03-05 11:03:50+00:00,False,False,Opportunity,1772717581.9591372,v9rfI0aubSVsZA,d1381e98-d9de-4c12-9863-b77e8c893c4f,424b1fee-9709-4315-85d9-5954058b4714,5f5ff932-5cd7-44de-b84f-1b0e758075ba,KP-47117-5,,,in_flight,,,,,,,Clinical IT,2026-03-05 11:03:50+00:00,2026-03-05 11:03:50+00:00
5,006T100000Q7GfTIAV,006T100000Q7GfTIAV,Clinical Transformation Initiative 6,Closed Won,2025-06-13,transformation initiative for Clinical Moderni...,2026-03-05 11:03:51+00:00,2026-03-05 11:03:51+00:00,True,True,False,False,100.0,Closed,Closed,False,005f60000029rvfAAA,005f60000029rvfAAA,005f60000029rvfAAA,2026-03-05 11:03:51+00:00,0,2,2025,2025 2,2026-03-05 11:03:51+00:00,2026-03-05 11:03:51+00:00,False,False,Opportunity,1772717581.9591372,dQBJfBo1TEa1+A,89ec8db4-9771-40b0-89f7-9ac822ee31bd,424b1fee-9709-4315-85d9-5954058b4714,5f5ff932-5cd7-44de-b84f-1b0e758075ba,KP-13840-6,,,closed,,,,,,,Platform Eng,2026-03-05 11:03:51+00:00,2026-03-05 11:03:51+00:00
6,006T100000Q7CiJIAV,006T100000Q7CiJIAV,Clinical Regulatory Initiative 7,Prospecting,2026-08-08,regulatory initiative for Clinical Modernizati...,2026-03-05 11:03:52+00:00,2026-03-05 11:03:52+00:00,False,False,False,False,0.0,Closed,Closed,False,005f60000029rvfAAA,005f60000029rvfAAA,005f60000029rvfAAA,2026-03-05 11:03:52+00:00,0,3,2026,2026 3,2026-03-05 11:03:52+00:00,2026-03-05 11:03:52+00:00,False,False,Opportunity,1772717581.9591372,Qr6vD3wPK6sq5w,21a98832-bc27-4825-9ea0-ac0542a73aa6,424b1fee-9709-4315-85d9-5954058b4714,5f5ff932-5cd7-44de-b84f-1b0e758075ba,KP-30845-7,,,approved,,,,,,,Ops IT,2026-03-05 11:03:52+00:00,2026-03-05 11:03:52+00:00
7,006T100000Q7DckIAF,006T100000Q7DckIAF,Clinical Regulatory Initiative 8,Closed Won,2025-06-18,regulatory initiative for Clinical Modernizati...,2026-03-05 11:03:53+00:00,2026-03-05 11:03:53+00:00,True,True,False,False,100.0,Closed,Closed,False,005f60000029rvfAAA,005f60000029rvfAAA,005f60000029rvfAAA,2026-03-05 11:03:53+00:00,0,2,2025,2025 2,2026-03-05 11:03:53+00:00,2026-03-05 11:03:53+00:00,False,False,Opportunity,1772717581.9591372,Eryg3o/YVMsvEQ,7b090062-5832-4872-9210-e67ab797b838,424b1fee-9709-4315-85d9-5954058b4714,5f5ff932-5cd7-44de-b84f-1b0e758075ba,KP-97587-8,,,closed,,,,,,,Digital Health,2026-03-05 11:03:53+00:00,2026-03-05 11:03:53+00:00
8,006T100000Q7Og9IAF,006T100000Q7Og9IAF,Clinical Modernization Initiative 9,Proposal/Price Quote,2025-05-17,modernization initiative for Clinical Moderniz...,2026-03-05 11:03:54+00:00,2026-03-05 11:03:54+00:00,False,False,False,False,0.0,Closed,Closed,False,005f60000029rvfAAA,005f60000029rvfAAA,005f60000029rvfAAA,2026-03-05 11:03:54+00:00,0,2,2025,2025 2,2026-03-05 11:03:54+00:00,2026-03-05 11:03:54+00:00,False,False,Opportunity,1772717581.9591372,8xqvzv3XdXYUUQ,c752427c-6e45-48c4-9049-c29f94958a08,424b1fee-9709-4315-85d9-5954058b4714,5f5ff932-5cd7-44de-b84f-1b0e758075ba,KP-60454-9,,,in_flight,,,,,,,Platform Eng,2026-03-05 11:03:54+00:00,2026-03-05 11:03:54+00:00
9,006T100000Q7GKXIA3,006T100000Q7GKXIA3,Clinical Transformation Initiative 10,Proposal/Price Quote,2026-12-05,transformation initiative for Clinical Moderni...,2026-03-05 11:03:55+00:00,2026-03-05 11:03:55+00:00,False,False,False,False,0.0,Closed,Closed,False,005f60000029rvfAAA,005f60000029rvfAAA,005f60000029rvfAAA,2026-03-05 11:03:55+00:00,0,4,2026,2026 4,2026-03-05 11:03:55+00:00,2026-03-05 11:03:55+00:00,False,False,Opportunity,1772717581.9591372,ouwglBjb7t1o9Q,547738b8-ef2a-400a-9868-aba82048ebbc,424b1fee-9709-4315-85d9-5954058b4714,5f5ff932-5cd7-44de-b84f-1b0e758075ba,KP-59267-10,,,in_flight,,,,,,,Ops IT,2026-03-05 11:03:55+00:00,2026-03-05 11:03:55+00:00

In [6]:
df.shape

(10, 47)

In [8]:
df['sponsor_person_id'].value_counts()

sponsor_person_id
    10
Name: count, dtype: int64

In [9]:
df['owning_org'].value_counts()

owning_org
Platform Eng      4
Clinical IT       2
Digital Health    2
Ops IT            2
Name: count, dtype: int64

In [11]:
df.isna().sum()

pk                               0
salesforce_id                    0
name                             0
stage_name                       0
close_date                       0
description                      0
created_date                     0
last_modified_date               0
is_closed                        0
is_won                           0
is_deleted                       0
is_private                       0
probability                      0
forecast_category                0
forecast_category_name           0
has_opportunity_line_item        0
owner_id                         0
created_by_id                    0
last_modified_by_id              0
system_modstamp                  0
push_count                       0
fiscal_quarter                   0
fiscal_year                      0
fiscal                           0
last_viewed_date                 0
last_referenced_date             0
has_open_activity                0
has_overdue_task                 0
_object                          0
_nilus_load_id                   0
_nilus_id                        0
project_id                       0
portfolio_id                     0
program_id                       0
project_code                     0
project_name                     0
project_type                     0
lifecycle_state                  0
stage                            0
start_date                       0
end_date                         0
strategic_alignment_flag         0
business_value_validated_flag    0
sponsor_person_id                0
owning_org                       0
created_at                       0
updated_at                       0
dtype: int64

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 47 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   pk                             10 non-null     object
 1   salesforce_id                  10 non-null     object
 2   name                           10 non-null     object
 3   stage_name                     10 non-null     object
 4   close_date                     10 non-null     object
 5   description                    10 non-null     object
 6   created_date                   10 non-null     datetime64[ns, UTC]
 7   last_modified_date             10 non-null     datetime64[ns, UTC]
 8   is_closed                      10 non-null     bool
 9   is_won                         10 non-null     bool
 10  is_deleted                     10 non-null     bool
 11  is_private                     10 non-null     bool
 12  probability                    10 non-null     float64
 13  forecast_category              10 non-null     object
 14  forecast_category_name         10 non-null     object
 15  has_opportunity_line_item      10 non-null     bool
 16  owner_id                       10 non-null     object
 17  created_by_id                  10 non-null     object
 18  last_modified_by_id            10 non-null     object
 19  system_modstamp                10 non-null     datetime64[ns, UTC]
 20  push_count                     10 non-null     int64
 21  fiscal_quarter                 10 non-null     int64
 22  fiscal_year                    10 non-null     int64
 23  fiscal                         10 non-null     object
 24  last_viewed_date               10 non-null     datetime64[ns, UTC]
 25  last_referenced_date           10 non-null     datetime64[ns, UTC]
 26  has_open_activity              10 non-null     bool
 27  has_overdue_task               10 non-null     bool
 28  _object                        10 non-null     object
 29  _nilus_load_id                 10 non-null     object
 30  _nilus_id                      10 non-null     object
 31  project_id                     10 non-null     object
 32  portfolio_id                   10 non-null     object
 33  program_id                     10 non-null     object
 34  project_code                   10 non-null     object
 35  project_name                   10 non-null     object
 36  project_type                   10 non-null     object
 37  lifecycle_state                10 non-null     object
 38  stage                          10 non-null     object
 39  start_date                     10 non-null     object
 40  end_date                       10 non-null     object
 41  strategic_alignment_flag       10 non-null     object
 42  business_value_validated_flag  10 non-null     object
 43  sponsor_person_id              10 non-null     object
 44  owning_org                     10 non-null     object
 45  created_at                     10 non-null     datetime64[ns, UTC]
 46  updated_at                     10 non-null     datetime64[ns, UTC]
dtypes: bool(7), datetime64[ns, UTC](7), float64(1), int64(3), object(29)
memory usage: 3.3+ KB

### zendesk_tickets_resource

In [15]:
from trino.dbapi import connect
from trino.auth import BasicAuthentication
import pandas as pd

# Connect to Trino
conn = connect(
    host="tcp.known-racer.mydataos.com",
    port=7432,
    auth=BasicAuthentication(
        "gunasekaranraja",
        "ZGF0YV9tb2RlbGVyLmM0MTQ0MzU0LWNhYmYtNDM0Zi1iYzFhLTI1OWFjYTFlMTYxMA=="
    ),
    http_scheme="https",
    http_headers={"cluster-name": "minervac"}
)

# Execute query
cur = conn.cursor()
cur.execute("""
                SELECT * FROM "icebase"."portfolio_intel".zendesk_tickets_resource LIMIT 10
            """)

# Get column names from cursor description
column_names = [desc[0] for desc in cur.description]

# Fetch rows and convert to DataFrame
rows = cur.fetchall()
zendesk = pd.DataFrame(rows, columns=column_names)

# df
# Save to CSV
# df.to_csv("manage_upload.csv", index=False)

# Print the DataFrame
# print(df)
zendesk

,pk,ticket_id,subject,description,status,priority,type,external_id,tags,requester_id,assignee_id,group_id,created_at,updated_at,url,via_channel,_nilus_load_id,_nilus_id,unplanned_work_id,work_class,effort_unit,opened_date,resolved_date,assignment_group_id,app_id,effort_proxy,sla_breach_flag
0,1,1,SAMPLE: How does Zendesk work,"Hello, let's see how you or your agents can ea...",solved,normal,,,zendesk_accelerated_setup,34432209786269,34432154794013,34432195823645,2026-03-06 07:14:06+00:00,2026-03-06 07:14:15+00:00,https://tmdc-68419.zendesk.com/api/v2/tickets/...,sample_ticket,1772782775.3423684,OOnM47TbqbALuw,,,,,,,,,
1,2,2,Clinical Modernization Initiative 1 Incident 1,Work class: other\nPriority: P4\nStatus: resol...,solved,low,question,75ae2b7c-7127-46ec-9195-19ae842cdc01,"ingested,intent__software__issue_generic__erro...",34432154794013,34432154794013,34432195823645,2026-03-06 07:16:51+00:00,2026-03-06 07:16:56+00:00,https://tmdc-68419.zendesk.com/api/v2/tickets/...,api,1772782775.3423684,O29tAKXf+dBjfw,75ae2b7c-7127-46ec-9195-19ae842cdc01,other,hours,2025-09-27T06:00:00+00:00,2025-10-01T03:00:00+00:00,a89ce759-5f3f-45eb-a701-b526c5b0049f,c8de08bd-6972-40e1-b17f-994e7e1d1073,40.21,False
2,3,3,Clinical Modernization Initiative 1 Incident 2,Work class: incident\nPriority: P3\nStatus: re...,solved,normal,incident,0423ede9-d9d7-42ae-8150-1591175b37a2,"incident,ingested,intent__software__issue_gene...",34432154794013,34432154794013,34432195823645,2026-03-06 07:16:53+00:00,2026-03-06 07:16:56+00:00,https://tmdc-68419.zendesk.com/api/v2/tickets/...,api,1772782775.3423684,V/WS8GhPa90lYg,0423ede9-d9d7-42ae-8150-1591175b37a2,incident,hours,2026-06-09T06:00:00+00:00,2026-06-11T14:00:00+00:00,a89ce759-5f3f-45eb-a701-b526c5b0049f,74b4cbd5-1768-464e-bd56-6326a7bbff50,41.38,False
3,4,4,Clinical Modernization Initiative 1 Incident 3,Work class: incident\nPriority: P3\nStatus: cl...,closed,normal,incident,5bc66742-e39d-4043-a505-f72d859497cf,"incident,ingested,p3,portfolio-intelligence",34432154794013,34432154794013,34432195823645,2026-03-06 07:16:55+00:00,2026-03-06 07:16:55+00:00,https://tmdc-68419.zendesk.com/api/v2/tickets/...,api,1772782775.3423684,H4E9XjDzFQ4CDQ,5bc66742-e39d-4043-a505-f72d859497cf,incident,count,2025-02-11T06:00:00+00:00,2025-02-18T00:00:00+00:00,fc1e5cbc-95a1-4fa0-81ad-c40bc876c33c,74b4cbd5-1768-464e-bd56-6326a7bbff50,5.43,False
4,5,5,Clinical Modernization Initiative 1 Incident 4,Work class: incident\nPriority: P1\nStatus: in...,open,urgent,incident,a39dfee5-9205-47c1-8904-6e56e2bf68ea,"incident,ingested,intent__software__issue_gene...",34432154794013,34432154794013,34432195823645,2026-03-06 07:16:57+00:00,2026-03-06 07:17:03+00:00,https://tmdc-68419.zendesk.com/api/v2/tickets/...,api,1772782775.3423684,dCb2vl9/9RHynA,a39dfee5-9205-47c1-8904-6e56e2bf68ea,incident,count,2024-02-28T06:00:00+00:00,2024-03-06T19:00:00+00:00,da34a67b-a07b-42c3-adb1-4ec915995217,c8de08bd-6972-40e1-b17f-994e7e1d1073,20.53,False
5,6,6,Clinical Modernization Initiative 2 Incident 1,Work class: incident\nPriority: P4\nStatus: in...,open,low,incident,0b2a814e-fc9a-4719-b616-4d01c1c8f1d5,"incident,ingested,intent__software__issue_gene...",34432154794013,34432154794013,34432195823645,2026-03-06 07:16:59+00:00,2026-03-06 07:17:03+00:00,https://tmdc-68419.zendesk.com/api/v2/tickets/...,api,1772782775.3423684,KYoEy+jsVE5suA,0b2a814e-fc9a-4719-b616-4d01c1c8f1d5,incident,hours,2026-05-04T06:00:00+00:00,2026-05-09T08:00:00+00:00,852c943b-d88c-4f8a-b448-99915ecbdbf3,dbeccfd3-e8fb-4cb5-87e1-2edc9534901c,16.42,False
6,7,7,Clinical Modernization Initiative 2 Incident 2,Work class: change\nPriority: P3\nStatus: in_p...,open,normal,task,801f61ed-bc68-4528-8e55-844b16491812,"change,ingested,intent__software__issue_generi...",34432154794013,34432154794013,34432195823645,2026-03-06 07:17:01+00:00,2026-03-06 07:17:13+00:00,https://tmdc-68419.zendesk.com/api/v2/tickets/...,api,1772782775.3423684,wta8KRvCqMCP9w,801f61ed-bc68-4528-8e55-844b16491812,change,hours,2024-08-12T06:00:00+00:00,—,da34a67b-a07b-42c3-adb1-4ec915995217,2ef7e8a3-cefa-450b-a13a-a862fdcf24d1,6.07,False
7,8,8,Clinical Modernization Initiative 2 Incident 3,Work class: change\nPriority: P2\nStatus: clos...,closed,high,task,b2aac8e9-66a5-4847-8719-1b32f8af372a,"change,ingested,p2,portfolio-intelligence",34432154794013,34432154794013,34432195823645,2026-03-06 07:17:03+00:00,2026-03-06 07:17:03+00:00,https://tmdc-68419.zendesk.com/api/v2/tickets/...,api,1772782775.3423684,PgbcTnhBmbLTrQ,b2aac8e9-66a5-4847-8719-1b32f8af372a,change,count,2024-04-14T06:00:00+00:00,2024-04-17T12:00:00+00:00,852c943b-d88c-4f8a-b448-99915ecbdbf3,2ef7e8a3-cefa-450b-a13a-a862fdcf24d1,25.77,False
8,9,9,Clinical Modernization Initiative 2 Incident 4,Work class: incident\nPriority: P4\nStatus: cl...,closed,low,incident,7a3d8e1c-e667-4546-b7c7-61cad700223a,"incident,ingested,p4,portfolio-intelligence",34432154794013,34432154794013,34432195823645,2026-03-06 07:17:05+00:00,2026-03-06 07:17:05+00:00,https://tmdc-68419.zendesk.com/api/v2/tickets/...,api,1772782775.3423684,wK76glRrgjAO9w,7a3d8e1c-e667-4546-b7c7-61cad700223a,incident,hours,2026-05-21T06:00:00+00:00,—,e15b2445-eff9-4104-b589-67aec1931120,2ef7e8a3-cefa-450b-a13a-a862fdcf24d1,20.49,False
9,10,10,Clinical Modernization Initiative 2 Incident 5,Work class: change\nPriority: P3\nStatus: clos...,closed,normal,task,b062f1f1-2a25-452e-acdf-2c1c8571339a,"change,ingested,p3,portfolio-intelligence",34432154794013,34432154794013,34432195823645,2026-03-06 07:17:07+00:00,2026-03-06 07:17:07+00:00,https://tmdc-68419.zendesk.com/api/v2/tickets/...,api,1772782775.3423684,9SjucAkPn4eRRg,b062f1f1-2a25-452e-acdf-2c1c8571339a,change,count,2026-04-01T06:00:00+00:00,—,00e8432a-4836-4b0b-9733-e835f1efa187,dbeccfd3-e8fb-4cb5-87e1-2edc9534901c,33.91,False

### jira_issues_resource

In [16]:
from trino.dbapi import connect
from trino.auth import BasicAuthentication
import pandas as pd

# Connect to Trino
conn = connect(
    host="tcp.known-racer.mydataos.com",
    port=7432,
    auth=BasicAuthentication(
        "gunasekaranraja",
        "ZGF0YV9tb2RlbGVyLmM0MTQ0MzU0LWNhYmYtNDM0Zi1iYzFhLTI1OWFjYTFlMTYxMA=="
    ),
    http_scheme="https",
    http_headers={"cluster-name": "minervac"}
)

# Execute query
cur = conn.cursor()
cur.execute("""
                SELECT * FROM "icebase"."portfolio_intel".jira_issues_resource LIMIT 10
            """)

# Get column names from cursor description
column_names = [desc[0] for desc in cur.description]

# Fetch rows and convert to DataFrame
rows = cur.fetchall()
jira_issues_resource = pd.DataFrame(rows, columns=column_names)

# df
# Save to CSV
# df.to_csv("manage_upload.csv", index=False)

# Print the DataFrame
# print(df)
jira_issues_resource

,pk,issue_id,issue_key,summary,description,status,issue_type,project_key,created_at,updated_at,url,_nilus_load_id,_nilus_id,planned_work_id,project_id,owning_team_id,work_type,effort_unit,start_date,due_date,completed_date,effort_estimate,remaining_estimate,delivery_tool
0,PORT-51,10291,PORT-51,Clinical Modernization Initiative 1 Work 1,planned_work_id: a2c3bf78-e6d8-466e-b1f9-6b76b...,To Do,Task,PORT,2026-03-05T18:33:07.215+,2026-03-05T18:33:07.306+,https://yogesh-khangode.atlassian.net/rest/api...,1772716150.5479898,wBVrL5ZBO87xqw,a2c3bf78-e6d8-466e-b1f9-6b76b62651e7,3a7051f4-6b57-46c0-b378-d9f316dcf5bc,e294dd39-6419-410c-ac9c-3389fdeed6d4,task,hours,2026-12-25,2027-02-14,,60.65,35.2,jira
1,PORT-52,10292,PORT-52,Clinical Modernization Initiative 1 Work 2,planned_work_id: af55af26-7fc0-4554-ae7f-a2226...,To Do,Task,PORT,2026-03-05T18:33:09.437+,2026-03-05T18:33:09.512+,https://yogesh-khangode.atlassian.net/rest/api...,1772716150.5479898,Aw1syot8M9WU9Q,af55af26-7fc0-4554-ae7f-a22268f07ab9,3a7051f4-6b57-46c0-b378-d9f316dcf5bc,512e2bba-695a-4ab5-8c01-da282a3c3673,feature,story_points,2026-10-01,2026-10-18,,19.67,10.77,jira
2,PORT-53,10293,PORT-53,Clinical Modernization Initiative 1 Work 3,planned_work_id: b3aa649d-8cff-4c1b-9f1e-74f21...,To Do,Task,PORT,2026-03-05T18:33:11.470+,2026-03-05T18:33:11.557+,https://yogesh-khangode.atlassian.net/rest/api...,1772716150.5479898,3Zn0XBboU94L8w,b3aa649d-8cff-4c1b-9f1e-74f219ae56df,3a7051f4-6b57-46c0-b378-d9f316dcf5bc,ff53edc9-a218-4ef7-b2e1-94fc98e6dab0,feature,hours,2026-06-09,2026-08-21,,98.24,21.49,ado
3,PORT-54,10294,PORT-54,Clinical Modernization Initiative 1 Work 4,planned_work_id: 85d69242-c8f5-470e-b780-87e5a...,To Do,Task,PORT,2026-03-05T18:33:13.600+,2026-03-05T18:33:13.682+,https://yogesh-khangode.atlassian.net/rest/api...,1772716150.5479898,b5Va8c+msXZy6w,85d69242-c8f5-470e-b780-87e5a3917754,3a7051f4-6b57-46c0-b378-d9f316dcf5bc,219550b4-68c3-4364-8b18-bef15036b2b2,story,hours,2026-09-23,2026-12-15,,30.03,20.54,jira
4,PORT-55,10295,PORT-55,Clinical Modernization Initiative 1 Work 5,planned_work_id: a0946d24-a741-40df-a5ac-a6169...,To Do,Task,PORT,2026-03-05T18:33:15.581+,2026-03-05T18:33:15.662+,https://yogesh-khangode.atlassian.net/rest/api...,1772716150.5479898,5UeeFCzR3F0reQ,a0946d24-a741-40df-a5ac-a6169b3fa1fb,3a7051f4-6b57-46c0-b378-d9f316dcf5bc,0757a54d-d5ae-4b98-a3da-182e0c4eae59,feature,story_points,2026-10-28,2026-11-27,,3.87,2.53,ado
5,PORT-56,10296,PORT-56,Clinical Modernization Initiative 1 Work 6,planned_work_id: f5b499c9-5125-4d3e-9937-8c1a7...,To Do,Task,PORT,2026-03-05T18:33:17.583+,2026-03-05T18:33:17.664+,https://yogesh-khangode.atlassian.net/rest/api...,1772716150.5479898,X6O6bAlLa4RnYA,f5b499c9-5125-4d3e-9937-8c1a75285ba3,3a7051f4-6b57-46c0-b378-d9f316dcf5bc,746ec056-a583-4966-bebd-ecf7358ff173,task,story_points,2026-12-22,2027-01-25,2027-01-15,49.15,0.0,jira
6,PORT-57,10297,PORT-57,Clinical Modernization Initiative 1 Work 7,planned_work_id: f85c92fe-4100-4b1d-affc-402f5...,To Do,Task,PORT,2026-03-05T18:33:19.728+,2026-03-05T18:33:19.823+,https://yogesh-khangode.atlassian.net/rest/api...,1772716150.5479898,9kDsLymbfWUfxg,f85c92fe-4100-4b1d-affc-402f550642d9,3a7051f4-6b57-46c0-b378-d9f316dcf5bc,0757a54d-d5ae-4b98-a3da-182e0c4eae59,epic,count,2026-12-05,2026-12-15,,29.6,5.05,ado
7,PORT-58,10298,PORT-58,Clinical Modernization Initiative 1 Work 8,planned_work_id: 52686087-110a-4cb4-bc81-db585...,To Do,Task,PORT,2026-03-05T18:33:21.859+,2026-03-05T18:33:21.969+,https://yogesh-khangode.atlassian.net/rest/api...,1772716150.5479898,2kdthuYiOZFiIQ,52686087-110a-4cb4-bc81-db585edd8ec8,3a7051f4-6b57-46c0-b378-d9f316dcf5bc,8311de74-1c1a-42bf-a96e-3b242b07ec84,story,hours,2026-08-16,2026-11-13,,77.11,65.62,ado
8,PORT-59,10299,PORT-59,Clinical Modernization Initiative 1 Work 9,planned_work_id: 8109a365-34e4-469c-b570-d0a20...,To Do,Task,PORT,2026-03-05T18:33:23.885+,2026-03-05T18:33:23.949+,https://yogesh-khangode.atlassian.net/rest/api...,1772716150.5479898,EspW9BqYuj7ypw,8109a365-34e4-469c-b570-d0a20d02b564,3a7051f4-6b57-46c0-b378-d9f316dcf5bc,836450f0-df7a-4b50-bcd8-a94e598cf84e,feature,hours,2026-10-18,2026-12-27,,8.18,4.86,jira
9,PORT-60,10300,PORT-60,Clinical Modernization Initiative 1 Work 10,planned_work_id: 9e0111b4-d099-4439-89ba-ae85b...,To Do,Task,PORT,2026-03-05T18:33:25.853+,2026-03-05T18:33:25.923+,https://yogesh-khangode.atlassian.net/rest/api...,1772716150.5479898,fxhMkZ2VigoTIA,9e0111b4-d099-4439-89ba-ae85ba5a8d2f,3a7051f4-6b57-46c0-b378-d9f316dcf5bc,0757a54d-d5ae-4b98-a3da-182e0c4eae59,feature,story_points,2026-11-02,2027-01-08,2027-01-03,82.68,0.0,ado

### servicenow_incidents_resource

In [17]:
from trino.dbapi import connect
from trino.auth import BasicAuthentication
import pandas as pd

# Connect to Trino
conn = connect(
    host="tcp.known-racer.mydataos.com",
    port=7432,
    auth=BasicAuthentication(
        "gunasekaranraja",
        "ZGF0YV9tb2RlbGVyLmM0MTQ0MzU0LWNhYmYtNDM0Zi1iYzFhLTI1OWFjYTFlMTYxMA=="
    ),
    http_scheme="https",
    http_headers={"cluster-name": "minervac"}
)

# Execute query
cur = conn.cursor()
cur.execute("""
                SELECT * FROM "icebase"."portfolio_intel".servicenow_incidents_resource LIMIT 10
            """)

# Get column names from cursor description
column_names = [desc[0] for desc in cur.description]

# Fetch rows and convert to DataFrame
rows = cur.fetchall()
servicenow_incidents_resource = pd.DataFrame(rows, columns=column_names)

# df
# Save to CSV
# df.to_csv("manage_upload.csv", index=False)

# Print the DataFrame
# print(df)
servicenow_incidents_resource

,pk,sys_id,number,short_description,description,urgency,impact,state,category,sys_created_on,sys_updated_on,closed_at,ridac_id,project_id,ridac_type,severity,probability,impact_area,owner_person_id,status,created_date,resolved_date,created_at,updated_at,_nilus_load_id,_nilus_id,closed_at__v_text
0,1c741bd70b2322007518478d83673af3,1c741bd70b2322007518478d83673af3,INC0000060,Unable to connect to email,I am unable to connect to the email server. It...,2,2,7,inquiry,2016-12-12 15:19:57+00:00,2016-12-14 02:46:44+00:00,2016-12-14 02:46:44+00:00,,,,,,,,,,,,,1773647063.6958334,KZg9tZthh9pbpA,None
1,46e18c0fa9fe19810066a0083f76bd56,46e18c0fa9fe19810066a0083f76bd56,INC0000014,Missing my home directory,Logged in and didn't see my home directory. Lo...,1,1,7,inquiry,2025-10-07 23:38:40+00:00,2026-01-06 13:02:24+00:00,2026-01-06 13:02:24+00:00,,,,,,,,,,,,,1773647063.6958334,nKHEbaxXpxwY6w,None
2,46ee0924a9fe198100f1cf78c198454a,46ee0924a9fe198100f1cf78c198454a,INC0000021,New employee hire,We have a new hire starting on Monday. She wil...,3,3,7,inquiry,2025-10-18 23:52:18+00:00,2026-01-05 19:56:12+00:00,2025-10-17 23:52:17+00:00,,,,,,,,,,,,,1773647063.6958334,0zvBXhBcW0k9oQ,None
3,46ee8c2fa9fe198100623592c70d643e,46ee8c2fa9fe198100623592c70d643e,INC0000024,Issue with a web page on wiki,The landing page for our internal wiki isn't l...,3,3,7,inquiry,2025-10-18 23:53:13+00:00,2026-01-05 20:15:44+00:00,2025-10-18 23:53:08+00:00,,,,,,,,,,,,,1773647063.6958334,MJQWxQfq8u4lew,None
4,1c832706732023002728660c4cf6a7b9,1c832706732023002728660c4cf6a7b9,INC0009002,My computer is not detecting the headphone device,My computer is not detecting the headphone dev...,2,2,7,Hardware,2018-09-16 12:50:05+00:00,2026-01-06 13:02:23+00:00,2018-12-10 03:29:08+00:00,,,,,,,,,,,,,1773647063.6958334,YR0Brw9t+2vyBQ,None
5,46b66a40a9fe198101f243dfbc79033d,46b66a40a9fe198101f243dfbc79033d,INC0000009,Reset my password,I can't remember my password and need to log i...,1,1,7,inquiry,2025-10-18 22:51:33+00:00,2026-01-05 20:16:04+00:00,2025-10-13 22:55:16+00:00,,,,,,,,,,,,,1773647063.6958334,vWCgGmlCwxcxIQ,None
6,46b9490da9fe1981003c938dab89bda3,46b9490da9fe1981003c938dab89bda3,INC0000010,Need Oracle 10GR2 installed,Currently running 10GR1 and need to upgrade to...,3,2,7,database,2025-10-18 22:54:41+00:00,2026-01-05 20:16:35+00:00,2025-10-11 22:54:55+00:00,,,,,,,,,,,,,1773647063.6958334,qiwPXWSnD4DX3A,None
7,46c03489a9fe19810148cd5b8cbf501e,46c03489a9fe19810148cd5b8cbf501e,INC0000011,Need new Blackberry set up,I'm replacing my old phone with a Blackberry a...,2,2,7,inquiry,2025-10-18 23:02:15+00:00,2026-01-05 19:56:31+00:00,2025-10-17 23:02:54+00:00,,,,,,,,,,,,,1773647063.6958334,c3lrmgY0avxDjA,None
8,46c88ac1a9fe1981014de1c831fbcf6d,46c88ac1a9fe1981014de1c831fbcf6d,INC0000012,Customer didn't receive eFax,I tried sending a fax to a customer through th...,3,3,7,software,2025-10-18 23:11:21+00:00,2026-01-05 19:56:12+00:00,2025-10-13 23:12:02+00:00,,,,,,,,,,,,,1773647063.6958334,bB7kjx2qjwyAVA,None
9,46cebb88a9fe198101aee93734f9768b,46cebb88a9fe198101aee93734f9768b,INC0000013,EMAIL is slow when an attachment is involved,Noticing today that any time I send an email w...,1,1,7,inquiry,2025-10-18 23:18:07+00:00,2026-01-05 19:54:48+00:00,2025-10-18 23:18:40+00:00,,,,,,,,,,,,,1773647063.6958334,/C+6F2dGMUznvA,None

### SAP

In [18]:
from trino.dbapi import connect
from trino.auth import BasicAuthentication
import pandas as pd

# Connect to Trino
conn = connect(
    host="tcp.known-racer.mydataos.com",
    port=7432,
    auth=BasicAuthentication(
        "gunasekaranraja",
        "ZGF0YV9tb2RlbGVyLmM0MTQ0MzU0LWNhYmYtNDM0Zi1iYzFhLTI1OWFjYTFlMTYxMA=="
    ),
    http_scheme="https",
    http_headers={"cluster-name": "minervac"}
)

# Execute query
cur = conn.cursor()
cur.execute("""
                SELECT * FROM "icebase"."sandbox".sap_c4c_product LIMIT 10
            """)

# Get column names from cursor description
column_names = [desc[0] for desc in cur.description]

# Fetch rows and convert to DataFrame
rows = cur.fetchall()
sap = pd.DataFrame(rows, columns=column_names)

# df
# Save to CSV
# df.to_csv("manage_upload.csv", index=False)

# Print the DataFrame
# print(df)
sap

,metadata,object_id,product_id,uuid,language,language_text,description,product_category_id,status,status_text,usage,usage_text,division,division_text,base_uom,base_uom_text,created_by,last_changed_by,created_on,last_changed_on,created_by_uuid,last_changed_by_uuid,external_system,external_id,entity_last_changed_on,e_tag,product_attachment_folder,product_other_descriptions,product_plant_party,product_quantity_characteristics,product_quantity_conversion,product_sales_process_information,product_skill,product_text_collection,productl_global_trade_item_number,extraction_timestamp,data_source,object_type,pk,_nilus_load_id,_nilus_id
0,"{""uri"": ""https://sandbox.api.sap.com/sap/c4c/o...",00163E03A0701EE288BE9895233EBD27,P140100,00163E03-A070-1EE2-88BE-9895233EBD27,EN,English,GS Marengo Womens Mountain Bike,CUSTOMER-01,3,Blocked,,,,,EA,Each,SAP WORKER,Eddie Smoke,/Date(1351534600660)/,/Date(1422997623532)/,00163E03-A070-1EE2-88B6-F539A6B028F3,00163E03-A070-1EE2-88BA-39BD20F290B5,CRM,P140100,/Date(1422997623532)/,/Date(1468410092156)/,"{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...",2026-03-24 09:27:36.125867+00:00,sap_c4c_api,Product,00163E03A0701EE288BE9895233EBD27,1774344440.0265,WfJUPFvtmGLqTw
1,"{""uri"": ""https://sandbox.api.sap.com/sap/c4c/o...",00163E03A0701EE288BE9895233EDD27,P130101,00163E03-A070-1EE2-88BE-9895233EDD27,EN,English,Group Transit Services,CUSTOMER-01,3,Blocked,,,,,EA,Each,SAP WORKER,Eddie Smoke,/Date(1351534600660)/,/Date(1422997623532)/,00163E03-A070-1EE2-88B6-F539A6B028F3,00163E03-A070-1EE2-88BA-39BD20F290B5,CRM,P130101,/Date(1422997623532)/,/Date(1468410092156)/,"{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...",2026-03-24 09:27:36.128286+00:00,sap_c4c_api,Product,00163E03A0701EE288BE9895233EDD27,1774344440.0265,eIy0Qm6b/wkXww
2,"{""uri"": ""https://sandbox.api.sap.com/sap/c4c/o...",00163E03A0701EE288BE9895233EFD27,P130100,00163E03-A070-1EE2-88BE-9895233EFD27,EN,English,Monthly Single Passenger Pass,CUSTOMER-01,3,Blocked,,,,,EA,Each,SAP WORKER,Eddie Smoke,/Date(1351534600660)/,/Date(1422997623532)/,00163E03-A070-1EE2-88B6-F539A6B028F3,00163E03-A070-1EE2-88BA-39BD20F290B5,CRM,P130100,/Date(1422997623532)/,/Date(1468410092156)/,"{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...",2026-03-24 09:27:36.128445+00:00,sap_c4c_api,Product,00163E03A0701EE288BE9895233EFD27,1774344440.0265,6hkBzwO4m6B+dw
3,"{""uri"": ""https://sandbox.api.sap.com/sap/c4c/o...",00163E03A0701EE288BE9895233F1D27,P120101,00163E03-A070-1EE2-88BE-9895233F1D27,EN,English,19.7 Commercial Series Refrigerator,CUSTOMER-01,3,Blocked,,,,,EA,Each,SAP WORKER,Eddie Smoke,/Date(1351534600660)/,/Date(1422997622362)/,00163E03-A070-1EE2-88B6-F539A6B028F3,00163E03-A070-1EE2-88BA-39BD20F290B5,CRM,P120101,/Date(1422997622362)/,/Date(1468410092156)/,"{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...",2026-03-24 09:27:36.128577+00:00,sap_c4c_api,Product,00163E03A0701EE288BE9895233F1D27,1774344440.0265,mgYtfp+IRsNxTg
4,"{""uri"": ""https://sandbox.api.sap.com/sap/c4c/o...",00163E03A0701EE288BE9895233F3D27,P120100,00163E03-A070-1EE2-88BE-9895233F3D27,EN,English,51.2 Commercial Series Refrigerator,CUSTOMER-01,3,Blocked,,,,,EA,Each,SAP WORKER,Eddie Smoke,/Date(1351534600660)/,/Date(1422997622362)/,00163E03-A070-1EE2-88B6-F539A6B028F3,00163E03-A070-1EE2-88BA-39BD20F290B5,CRM,P120100,/Date(1422997622362)/,/Date(1468410092156)/,"{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...",2026-03-24 09:27:36.128665+00:00,sap_c4c_api,Product,00163E03A0701EE288BE9895233F3D27,1774344440.0265,fiDOA1jqEIPpjw
5,"{""uri"": ""https://sandbox.api.sap.com/sap/c4c/o...",00163E03A0701EE288BE9895233F5D27,P110101,00163E03-A070-1EE2-88BE-9895233F5D27,EN,English,International Flight Ticketing,CUSTOMER-01,3,Blocked,,,,,EA,Each,SAP WORKER,Eddie Smoke,/Date(1351534600660)/,/Date(1422997622362)/,00163E03-A070-1EE2-88B6-F539A6B028F3,00163E03-A070-1EE2-88BA-39BD20F290B5,CRM,P110101,/Date(1422997622362)/,/Date(1468410092156)/,"{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...",2026-03-24 09:27:36.128744+00:00,sap_c4c_api,Product,00163E03A0701EE288BE9895233F5D27,1774344440.0265,fsGRS4VFYTWI6A
6,"{""uri"": ""https://sandbox.api.sap.com/sap/c4c/o...",00163E03A0701EE288BE9895233F7D27,P110100,00163E03-A070-1EE2-88BE-9895233F7D27,EN,English,Domestic Flight Ticketing,CUSTOMER-01,3,Blocked,,,,,EA,Each,SAP WORKER,Eddie Smoke,/Date(1351534600660)/,/Date(1422997622362)/,00163E03-A070-1EE2-88B6-F539A6B028F3,00163E03-A070-1EE2-88BA-39BD20F290B5,CRM,P110100,/Date(1422997622362)/,/Date(1468410092156)/,"{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...",2026-03-24 09:27:36.128817+00:00,sap_c4c_api,Product,00163E03A0701EE288BE9895233F7D27,1774344440.0265,w+BmcgCue1NkqQ
7,"{""uri"": ""https://sandbox.api.sap.com/sap/c4c/o...",00163E03A0701EE288BE9895233F9D27,P100101,00163E03-A070-1EE2-88BE-9895233F9D27,EN,English,Unlimited Talk and Data Plan,CUSTOMER-01,3,Blocked,,,,,EA,Each,SAP WORKER,Eddie Smoke,/Date(1351534600660)/,/Date(1422997622362)/,00163E03-A070-1EE2-88B6-F539A6B028F3,00163E03-A070-1EE2-88BA-39BD20F290B5,CRM,P100101,/Date(1422997622362)/,/Date(1468410092156)/,"{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...",2026-03-24 09:27:36.128900+00:00,sap_c4c_api,Product,00163E03A0701EE288BE9895233F9D27,1774344440.0265,3OKqlDfy8sht9Q
8,"{""uri"": ""https://sandbox.api.sap.com/sap/c4c/o...",00163E03A0701EE288BE9895233FBD27,P100100,00163E03-A070-1EE2-88BE-9895233FBD27,EN,English,Basic Talk and Text Plan,CUSTOMER-01,3,Blocked,,,,,EA,Each,SAP WORKER,Eddie Smoke,/Date(1351534600660)/,/Date(1422997622362)/,00163E03-A070-1EE2-88B6-F539A6B028F3,00163E03-A070-1EE2-88BA-39BD20F290B5,CRM,P100100,/Date(1422997622362)/,/Date(1468410092156)/,"{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...",2026-03-24 09:27:36.128989+00:00,sap_c4c_api,Product,00163E03A0701EE288BE9895233FBD27,1774344440.0265,6DHBlj3hDCK/2A
9,"{""uri"": ""https://sandbox.api.sap.com/sap/c4c/o...",00163E03A0701EE288BE9895233FDD27,P140101,00163E03-A070-1EE2-88BE-9895233FDD27,EN,English,GS Mendocino Womens Mountain Bike,CUSTOMER-01,3,Blocked,,,,,EA,Each,SAP WORKER,Eddie Smoke,/Date(1351534600660)/,/Date(1422997623532)/,00163E03-A070-1EE2-88B6-F539A6B028F3,00163E03-A070-1EE2-88BA-39BD20F290B5,CRM,P140101,/Date(1422997623532)/,/Date(1468410092156)/,"{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...","{""__deferred"": {""uri"": ""https://sandbox.api.sa...",2026-03-24 09:27:36.129059+00:00,sap_c4c_api,Product,00163E03A0701EE288BE9895233FDD27,1774344440.0265,pYDA4zVHVIhnvg